# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "base16-builder-go-unstable-${version}";
  version = "2018-03-02";
  rev = "c36a9fdb4383cc55f3527e3b0a642e92d3b6cff6";

  goPackagePath = "base16-builder-go";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/belak/base16-builder-go";
    sha256 = "0dskg2sqazznvir0llxn6mi9sykc1m614msgrkdyk5pkbiiys0as";
  };

  goDeps = ./base16-builder-go-deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
