# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/Masterminds/vcs";
    fetch = {
      type = "git";
      url = "https://github.com/Masterminds/vcs";
      rev = "df81cd881f84b6bd2ed4e35cd16d41a4ff9ece17";
      sha256 = "07la98qirfzdnamg992iam751510rv9wm9safmvssbaaa4s5s3dy";
    };
  }
  {
    goPackagePath = "github.com/Sirupsen/logrus";
    fetch = {
      type = "git";
      url = "https://github.com/Sirupsen/logrus";
      rev = "a1f2e46d92096f9157fe71165f6f135d9f0b9c18";
      sha256 = "04gb5gdya4ny3brcmzhd2mmcs9mmds3gnc2dnh674af46934libk";
    };
  }
  {
    goPackagePath = "github.com/Unknwon/com";
    fetch = {
      type = "git";
      url = "https://github.com/Unknwon/com";
      rev = "da59b551951d50441ca26b7a8cd81317f34df87f";
      sha256 = "03xx2kwi8pmglblvfxasppyvpbscq8l1r03r6jfkgi8c2a8i01am";
    };
  }
  {
    goPackagePath = "github.com/cbroglie/mustache";
    fetch = {
      type = "git";
      url = "https://github.com/cbroglie/mustache";
      rev = "73b1f3905474dd28d480fbb3f1da71b625a58e76";
      sha256 = "1l0ggygsf07ffmgv1lhhhqpiq041jl1r1dqri4gliddc863pzyrz";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "a114f312e075f65bf30d6d9a1430113f857e543b";
      sha256 = "10lmi5ni06yijxg02fcic5b7ycjkia12yma4a4lz8a56j30wykx1";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "3ebe029320b2676d667ae88da602a5f854788a8a";
      sha256 = "11yxs0wqy70wj106fkz8r923yg4ncnc2mbw33v48zmlg4a1rasgp";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "a2144134853fc9a27a7b1e3eb4f19f1a76df13c9";
      sha256 = "0hjjk6k9dq7zllwsw9icdfbli12ii379q2lajd6l7lyw72wy28by";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "ac767d655b305d4e9612f5f6e33120b9176c4ad4";
      sha256 = "1ds29n5lh4j21hmzxz7vk7hv1k6sixc7f0zsdc9xqdg0j7d212zm";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "5420a8b6744d3b0345ab293f6fcba19c978f1183";
      sha256 = "0dwjrs2lp2gdlscs7bsrmyc5yf6mm4fvgw71bzr9mv2qrd2q73s1";
    };
  }
]
