# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ nixpkgs ? import<nixpkgs> {} }: with nixpkgs; rec {
  base16-builder-go = callPackage (import ./base16-builder-go.nix) {};
  base16-update = runCommand "base16-update" {
      nativeBuildInputs = [git];
      GIT_SSL_CAINFO = "${cacert}/etc/ssl/certs/ca-bundle.crt";
      } ''
      mkdir -p $out
      cd $out
      ${base16-builder-go}/bin/base16-builder-go update
      patch -d templates/emacs -p1 -i ${./base16-emacs.patch}
      find . -name '.git' -type d -prune -exec rm -fr {} \;
      '';
  base16-themes = let
    in runCommand "base16-themes" {
      } ''
      mkdir -p "$out"
      cp -R "${base16-update}/templates"/* "$out"/
      cd "$out"
      chmod +w * -R
      ${base16-builder-go}/bin/base16-builder-go build --sources-dir "${base16-update}/sources" --schemes-dir "${base16-update}/schemes" --templates-dir .
      find . -name '*.yaml' ! -name 'config.yaml' -type f -exec basename -s ".yaml" {} \; > schemes
    '';
}    
  

