#!/usr/bin/env bash

source ~/.profile
source ~/.bashrc

shopt -s expand_aliases

command -v nix-env || (echo "nix-env executable not found, aborting" && exit -1)

echo "Configuring nix channels"
nix-channel --add https://nixos.org/channels/nixos-unstable unstable
nix-channel --add https://nixos.org/channels/nixos-18.09 nixos-18.09

nix-channel --update

echo "Installing nix environment"
nixup
